name: Deployment with separate jobs
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Load & cache dependencies (via composite custom action)
        uses: ./.github/actions/cached-deps
      - name: Run ESLint
        run: yarn lint
      - name: Run tests
        run: yarn test:run
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file-in-job: ${{ steps.jsfile.outputs.script-file-in-step }}
    steps:
      - name: Get code
        uses: actions/checkout@v6
      - name: Cache dependencies
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - name: Build project
        run: yarn build
      - name: Publish JS filename
        id: jsfile
        run: |
          find .next/*.js -type f -execdir echo 'script-file-in-step={}' >> "$GITHUB_OUTPUT" ';'
      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: nextjs-build-artifacts
          include-hidden-files: true
          path: |
            .next
            public
            package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v8
        with:
          name: nextjs-build-artifacts
      - name: Output contents
        run: ls -la
      - name: Output JS filename
        run: echo "${{ needs.build.outputs.script-file-in-job }}"
      - name: Deploy code
        run: echo "Deploying code..."
  reusable_input:
    needs: deploy
    uses: ./.github/workflows/Reusable.yml
    with:
      artifact-name-input: nextjs-build-artifacts
  reusable_output:
    needs: reusable_input
    runs-on: ubuntu-latest
    steps:
      - name: Print reusable workflow output
        run: echo "${{ needs.reusable_input.outputs.result-output }}"
  report:
    needs: [test, build, deploy]
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "Running report job when previous job failed"
          echo "$GITHUB_CONTEXT"
